---
###
# SELinux enforcement
###
nginx_selinux: yes
# Set selinux policy and mode
nginx_selinux_policy: targeted
nginx_selinux_mode: permissive
# Reboot if required
nginx_selinux_reboot: yes

# Become root privileges on each task
nginx_become: yes

# Nginx version to install
nginx_version: 1.19.1

# Virtualhost server_name
nginx_site_name: example.com
# Virtualhost listen port
nginx_site_listen: 8080
