---
- name: Provision vagrant instance
  hosts: all
  become: yes
  tasks:
    - name: Install docker
      yum:
        name: docker
        state: present
    - name: 

  post_tasks:
    - debug:
        msg: |
          To connect to host, run:
          ssh -i ./.vagrant/machines/{{ ansible_hostname }}/virtualbox/private_key -p {{ ansible_ssh_port }} {{ item.name }}@{{ ansible_ssh_host }}
      loop: "{{ pamexec_users }}"
