---
- name: Converge
  hosts: all
  become: yes
  vars:
    selinux_mode: enforcing
    #nginx_selinux_mode: permissive
    nginx_selinux_seboolean: yes
    nginx_site_listen: 8080
  tasks:
    - name: "Include ansible-role-selinux"
      include_role:
        name: "ansible-role-selinux"
    - name: "Include ansible-role-nginx"
      include_role:
        name: "ansible-role-nginx"
  post_tasks:
    - name: Ensure nginx works
      uri:
        url: "http://127.0.0.1:{{ item }}"
      delegate_to: localhost
      become: no
      loop:
        - 8081
        - 8082
        - 8083
