---
- name: Enable selinux boolean httpd_can_network_connect
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
  when: nginx_selinux_seboolean | bool
  notify:
    - Restart nginx
